name: Deploy Wild West Launchpad

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found, skipping dependencies"
          fi
          
      - name: Build project
        env:
          SOLANA_RPC_ENDPOINT: ${{ secrets.SOLANA_RPC_ENDPOINT }}
          BASE_RPC_ENDPOINT: ${{ secrets.BASE_RPC_ENDPOINT }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Building Wild West Crypto Launchpad..."
          
          # Create production config with injected secrets
          cat > js/production-config.js << 'EOF'
          // Production configuration injected at build time from GitHub Secrets
          (function() {
            'use strict';
            
            // Secure configuration from GitHub Secrets
            window.PRODUCTION_CONFIG = {
              token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}',
              rpc: {
                solana: '${{ secrets.SOLANA_RPC_ENDPOINT }}',
                base: '${{ secrets.BASE_RPC_ENDPOINT }}'
              },
              injectedAt: new Date().toISOString(),
              source: 'github-actions'
            };
            
            // Update ENV_CONFIG if it exists
            if (window.ENV_CONFIG && typeof window.ENV_CONFIG.updateFromSecureAPI === 'function') {
              const secureConfigs = {
                github: { token: window.PRODUCTION_CONFIG.token },
                rpc: window.PRODUCTION_CONFIG.rpc
              };
              window.ENV_CONFIG.updateFromSecureAPI(secureConfigs);
              console.log('âœ… ENV_CONFIG updated with GitHub Secrets');
            }
            
            console.log('ðŸ” Production configuration loaded from GitHub Secrets');
            console.log('ðŸ“Š RPC Status:', {
              solana: !!window.PRODUCTION_CONFIG.rpc.solana,
              base: !!window.PRODUCTION_CONFIG.rpc.base
            });
          })();
          EOF
          
          echo "âœ… Production config generated with secrets"
          
      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
          
      - name: Notify deployment success
        run: |
          echo "ðŸš€ Wild West Launchpad deployed successfully!"
          echo "ðŸ“ Available at: https://cowboytbc.github.io/wildwest-launchpad/"
