name: Deploy Wild West Launchpad

on:
  push:
    branches: [ main, gh-pages ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found, skipping dependencies"
          fi
          
      - name: Build project
        run: |
          echo "Building Wild West Crypto Launchpad..."
          # Add any build steps if needed
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          
      - name: Notify deployment success
        run: |
          echo " Wild West Launchpad deployed successfully!"
          echo " Available at: https://cowboytbc.github.io/WILDWEST-BANNERS-PFPS/"
