name: Upload Image to Storage

on:
  repository_dispatch:
    types: [upload-image]

jobs:
  upload-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout storage repository
        uses: actions/checkout@v4
        with:
          repository: cjlovesbeverly/wildwest-banner-storage
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: storage

      - name: Decode and save image
        run: |
          cd storage
          echo "${{ github.event.client_payload.image }}" | base64 -d > "${{ github.event.client_payload.filename }}"

      - name: Create directory if needed
        run: |
          cd storage
          CATEGORY="${{ github.event.client_payload.category }}"
          case "$CATEGORY" in
            "project-logo") DIR="project-logos" ;;
            "project-banner") DIR="project-banners" ;;
            "trader-pfp") DIR="trader-pfps" ;;
            "banner-top") DIR="banners/top" ;;
            "banner-bottom") DIR="banners/bottom" ;;
            *) DIR="banners" ;;
          esac
          mkdir -p "$DIR"
          mv "${{ github.event.client_payload.filename }}" "$DIR/"

      - name: Commit and push
        run: |
          cd storage
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Upload ${{ github.event.client_payload.category }}: ${{ github.event.client_payload.filename }}"
          git push
